### ISSUE TITLE
Upgrading to keras 2.1.2 broke GruWithWeightNorm

### ISSUE THREAD

**Issue by szcom** [szcom/samplernn#1]
Worked in  Keras-2.0.5 but went broken in keras-2.1.2

` File "train_srnn.py", line 188, in <module>
    mlp_activation='relu')
  File "/Users/sz/deep/samplernn/srnn.py", line 262, in __init__
    self.slow_tier_model, initial_state=self.slow_rnn_h0)
  File "/Users/sz/anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py", line 522, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/Users/sz/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/sz/deep/samplernn/srnn.py", line 151, in call
    constants = self.get_constants(inputs, training=None)
AttributeError: 'GruWithWeightNorm' object has no attribute 'get_constants'`

**Comment by szcom** [comment]
workaround for now is to `pip install --upgrade keras==2.0.5`

**Comment by szcom** [comment]
fixed by 8ccd8aaabb48395f74ac97d9d04f152442fc48b4
